[changelog]
header = "## Registro de Mudancas\n"

footer = "Vilante Labs (c) 2025"

[git]
filter_unconventional = true
commit_parsers = [
    { message = "^feat", format = "Nova Funcionalidade: {commit.header}" },
    { message = "^fix", format = "Correcao de Bug: {commit.header}" },
    { message = "^docs", format = "Documentacao: {commit.header}" },
    { message = "^style", format = "Estilizacao: {commit.header}" },
    { message = "^refactor", format = "Refatoracao: {commit.header}" },
    { message = "^perf", format = "Melhoria de Performance: {commit.header}" },
    { message = "^test", format = "Testes: {commit.header}" },
    { message = "^chore", format = "Outras Mudancas: {commit.header}" },
    { message = "^ci", format = "CI/CD: {commit.header}" },
    { message = "^build", format = "Build: {commit.header}" }
]
tag_pattern = "v[0-9]+.*"
