name: Build and Release Video Frame Recorder

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Chocolatey and dependencies (LLVM and OpenCV)
      - name: Install dependencies via Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install llvm opencv --no-progress --confirm

      # Set OpenCV environment variables
      - name: Set OpenCV environment variables
        run: |
          echo "OPENCV_INCLUDE_PATHS=C:\\tools\\opencv\\build\\include" >> $env:GITHUB_ENV
          echo "OPENCV_LINK_LIBS=opencv_world4100" >> $env:GITHUB_ENV
          echo "OPENCV_LINK_PATHS=C:\\tools\\opencv\\build\\x64\\vc16\\lib" >> $env:GITHUB_ENV
          echo "C:\\tools\\opencv\\build\\x64\\vc16\\bin" >> $env:GITHUB_PATH

      # Setup Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable

      # Build project
      - name: Build project
        run: cargo build --release

      # Copy OpenCV DLL
      - name: Copy OpenCV DLL
        run: |
          copy "C:\\tools\\opencv\\build\\x64\\vc16\\bin\\opencv_world4100.dll" ".\\opencv_world4100.dll"

      # Package files into a ZIP
      - name: Package executable and DLL into a ZIP file
        run: |
          mkdir release_files
          copy target/release/video_frame_saver.exe release_files/
          copy opencv_world4100.dll release_files/
          powershell Compress-Archive -Path release_files\* -DestinationPath video_frame_saver-v${{ github.ref_name }}-windows-x64.zip

      # Upload ZIP to GitHub Release
      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: video_frame_saver-v${{ github.ref_name }}-windows-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
